favicon: null
name: 'Tamiami Orchid Festival '
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5979952649213374
  brandStrength: 0.311828
  rhythmicContrast: 0.403045407962054
  brandColors:
    - '#FFFFFF'
    - '#030102'
    - '#656576'
    - '#300165'
    - '#7728BE'
  lightness: 0.01921469159424305
typography_spectrum: 0.5394265
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5806451
analytics:
  twitter: null
  google: null
  facebook: null
