name: 'Tamiami Orchid Festival '
favicon: null
layout_spectrum: 0.5806451
typography_spectrum: 0.5394265
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 2016 Tamiami International Orchid Festival
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#030102'
    - '#656576'
    - '#300165'
    - '#7728BE'
  brandStrength: 0.311828
  lightness: 0.01921469159424305
  saturation: 0.5979952649213374
  rhythmicContrast: 0.403045407962054
purpose: []
